root: true
env:
  node: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - prettier
ignorePatterns:
  - dist
  - ".babel.config.js"
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  tsconfigRootDir: __dirname
